services:
  readseerr:
    build: .
    container_name: readseerr
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - readseerr-data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/readseerr.db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://192.168.1.37:3000}
      - COMICVINE_API_KEY=${COMICVINE_API_KEY}
      # Configuration de tes emails (Nodemailer)
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    networks:
      - media-stack

volumes:
  readseerr-data:
    driver: local

networks:
  media-stack:
    external: true
